<?php

namespace TMS\TasksManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	private function whereUserIs(\Doctrine\ORM\QueryBuilder $qb, $userid = null)
	{
		if ($userid !== null) {
			$qb->andWhere('t.id_user = :iduser')
				->setParameter('iduser', $userid);
		}
	}

	public function findAllRunningTasksOrderedByDueDate($userid = null)
	{
		$qb = $this->createQueryBuilder('t');
		//$this->whereUserIs($qb, $userid);
		return $qb->andWhere('t.date_completed IS NOT NULL')
					->orderBy('t.due_date', 'ASC')
					->getQuery()
					->getResult();
	}
	
	public function find($taskid, $userid = null)
	{
		$qb = $this->createQueryBuilder('t');
		//$this->whereUserIs($qb, $userid);
		return $qb->where('t.id == :id')
						->setParameter('id', $taskid)
						->getQuery()
						->getResult();
	}
}
