<?php

namespace TMS\TasksManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	private function whereUserIs(\Doctrine\ORM\QueryBuilder $qb, $username)
	{
		if ($username !== null) {
			$qb->innerJoin('TMS\UsersBundle\Entity\User', 'u', Join::WITH, 't.user = u.id')
				->andWhere('u.username = :username')
				->setParameter('username', $username);
		}
	}

	public function findAllRunningTasksOrderedByDueDate($username)
	{
		$qb = $this->createQueryBuilder('t');
		$this->whereUserIs($qb, $username);
		return $qb//->andWhere('t.date_completed IS NOT NULL')
					->orderBy('t.due_date', 'ASC')
					->getQuery()
					->getResult();
	}
	
	public function findUserTask($username, $taskid)
	{
		$qb = $this->createQueryBuilder('t');
		$this->whereUserIs($qb, $username);
		return $qb->andWhere('t.id = :id')
						->setParameter('id', $taskid)
						->getQuery()
						->getOneOrNullResult();
	}
	
	public function findNextTasks($username, $limit)
	{
		$qb = $this->createQueryBuilder('t');
		$this->whereUserIs($qb, $username);
		return $qb->andWhere('t.date_started IS NULL')
					->orderBy('t.due_date', 'ASC')
					//->setFirstResult($offset)
					->setMaxResults($limit)
					->getQuery()
					->getResult();
	}
	
	public function findTasksInProgress($username, $limit)
	{
		$qb = $this->createQueryBuilder('t');
		$this->whereUserIs($qb, $username);
		return $qb->andWhere('t.date_started IS NOT NULL')
					->andWhere('t.date_completed IS NULL')
					->orderBy('t.due_date', 'ASC')
					//->setFirstResult($offset)
					->setMaxResults($limit)
					->getQuery()
					->getResult();
	}
}
