tms_tasks_manager_homepage:
    pattern:  /{username}/tasks
    defaults: { _controller: TMSTasksManagerBundle:Default:index }

tms_tasks_manager_show:
    pattern:  /{username}/tasks/{taskid}
    defaults: { _controller: TMSTasksManagerBundle:Default:show }
    requirements:
        id:  \d+
