tms_tasks_manager_homepage:
    pattern:  /tasks
    defaults: { _controller: TMSTasksManagerBundle:Default:index }

tms_tasks_manager_show:
    pattern:  /tasks/{taskid}
    defaults: { _controller: TMSTasksManagerBundle:Default:show }
    requirements:
        taskid:  \d+

tms_tasks_manager_create:
    pattern:  /tasks/create
    defaults: { _controller: TMSTasksManagerBundle:Default:create }
