tms_tasks_manager_homepage:
    pattern:  /tasks
    defaults: { _controller: TMSTasksManagerBundle:Default:index }

tms_tasks_manager_show:
    pattern:  /tasks/{taskid}
    defaults: { _controller: TMSTasksManagerBundle:Default:show }
    requirements:
        taskid:  \d+

tms_tasks_manager_create:
    pattern:  /tasks/create
    defaults: { _controller: TMSTasksManagerBundle:Default:create }

tms_tasks_manager_edit:
    pattern:  /tasks/{taskid}/edit
    defaults: { _controller: TMSTasksManagerBundle:Default:edit }
    requirements:
        taskid:  \d+

tms_tasks_manager_delete:
    pattern:  /tasks/{taskid}/delete
    defaults: { _controller: TMSTasksManagerBundle:Default:delete }
    requirements:
        taskid:  \d+


# Task dependencies related routes
tms_tasks_manager_add_dep_form:
    pattern:  /tasks/add-dep-form
    defaults: { _controller: TMSTasksManagerBundle:Default:addDependenciesForm }
    requirements:
        _method: POST

tms_tasks_manager_add_dep:
    pattern:  /tasks/add-dep
    defaults: { _controller: TMSTasksManagerBundle:Default:addDependencies }
    requirements:
        _method: POST

tms_tasks_manager_remove_dep:
    pattern:  /tasks/remove-dep
    defaults: { _controller: TMSTasksManagerBundle:Default:removeDependencies }
    requirements:
        _method: POST
