parameters:
#    tms_tasks_manager.example.class: TMS\TasksManagerBundle\Example

services:
#    tms_tasks_manager.example:
#        class: %tms_tasks_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
