login:
    pattern:   /login
    defaults: { _controller: TMSUsersBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

tms_users:
    resource: "@TMSUsersBundle/Resources/config/routing.yml"
    prefix:   /

tms_tasks_manager:
    resource: "@TMSTasksManagerBundle/Resources/config/routing.yml"
    prefix:   /
