tms_users:
    resource: "@TMSUsersBundle/Resources/config/routing.yml"
    prefix:   /

tms_tasks_manager:
    resource: "@TMSTasksManagerBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /
    defaults: { _controller: TMSUsersBundle:Default:index }

logout:
    pattern:   /logout
