security:
    encoders:
        TMS\UsersBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: TMS\UsersBundle\Entity\User, property: username }
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:  ^/
            anonymous: true
            provider: user_db
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                default_target_path:            /
                username_parameter: user_login[username]
                password_parameter: user_login[password]
            logout:
                path:   /logout
                target: /
                # The following line is a temporary fix to a php bug with version under 5.4.11 : https://github.com/symfony/symfony/issues/5868
                # Probably usefull only for php sessions.
                invalidate_session: false
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/tasks, roles: ROLE_USER }
        
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
