tms_users_homepage:
    pattern:  /
    defaults: { _controller: TMSUsersBundle:Default:index }

tms_users_dashboard:
    pattern:  /dashboard
    defaults: { _controller: TMSUsersBundle:Default:dashboard }
